# Site settings
title:       OpenLaws
email:       kplessas@ceid.upatras.gr
author:      Kostas Plessas
description: "A Project Opening Greek Legislation to Citizens"
baseurl:     ""
url:         "http://www.openlaws.gr"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: OpenLawsGR

# Social icons
show_social_icons: true
github_username: OpenLawsGR
stackoverflow_id:
twitter_username: OpenLawsGR
google_plus_id:
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true
